name: Portfolio App CI/CD
on:
  push:
    branches:
      - main
env:
  CI: false
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Change Directory
        run: cd ../
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: build
